//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public string SundayForegroundColor {
            get {
                return ((string)(this["SundayForegroundColor"]));
            }
            set {
                this["SundayForegroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public string SaturdayForegroundColor {
            get {
                return ((string)(this["SaturdayForegroundColor"]));
            }
            set {
                this["SaturdayForegroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public string HolidayForegroundColor {
            get {
                return ((string)(this["HolidayForegroundColor"]));
            }
            set {
                this["HolidayForegroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGray")]
        public string ToDayBackgroundColor {
            get {
                return ((string)(this["ToDayBackgroundColor"]));
            }
            set {
                this["ToDayBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n          1948,9999,1,1,元旦\r\n          1966,9999,2,11,建国記念の日\r\n          2007,999" +
            "9,4,29,昭和の日\r\n          1948,9999,5,3,憲法記念日\r\n          2007,9999,5,4,みどりの日\r\n     " +
            "     1948,9999,5,5,こどもの日\r\n          1948,9999,11,3,文化の日\r\n          1948,9999,11," +
            "23,勤労感謝の日\r\n          1989,9999,12,23,天皇誕生日\r\n          2016,2016,1,11,成人の日\r\n     " +
            "     2016,2016,3,20,春分の日\r\n          2016,2016,3,21,春分の日の振替\r\n          2016,2016," +
            "7,18,海の日\r\n          2016,2016,8,11,山の日\r\n          2016,2016,9,19,敬老の日\r\n         " +
            " 2016,2016,9,22,秋分の日\r\n          2016,2016,10,10,体育の日\r\n          2017,2017,1,2,元旦" +
            "の振替\r\n          2017,2017,1,9,成人の日\r\n          2017,2017,3,20,春分の日\r\n          2017" +
            ",2017,7,17,海の日\r\n          2017,2017,8,11,山の日\r\n          2017,2017,9,18,敬老の日\r\n   " +
            "       2017,2017,9,23,秋分の日\r\n          2017,2017,10,9,体育の日\r\n          2018,2018,1" +
            ",8,成人の日\r\n          2018,2018,2,12,建国記念日の振替\r\n          2018,2018,3,21,春分の日\r\n     " +
            "     2018,2018,4,30,昭和の日の振替\r\n          2018,2018,7,16,海の日\r\n          2018,2018,8" +
            ",11,山の日\r\n          2018,2018,9,17,敬老の日\r\n          2018,2018,9,23,秋分の日\r\n         " +
            " 2018,2018,9,24,秋分の日の振替\r\n          2018,2018,10,8,体育の日\r\n          2018,2018,12,2" +
            "4,天皇誕生日の振替\r\n          2019,2019,1,14,成人の日\r\n          2019,2019,3,21,春分の日\r\n      " +
            "    2019,2019,5,6,こどもの日の振替\r\n          2019,2019,7,15,海の日\r\n          2019,2019,8," +
            "11,山の日\r\n          2019,2019,8,12,山の日の振替\r\n          2019,2019,9,16,敬老の日\r\n        " +
            "  2019,2019,9,23,秋分の日\r\n          2019,2019,10,14,体育の日\r\n          2019,2019,11,4," +
            "文化の日の振替\r\n          2020,2020,1,13,成人の日\r\n          2020,2020,3,20,春分の日\r\n         " +
            " 2020,2020,5,4,憲法記念日の振替\r\n          2020,2020,7,20,海の日\r\n          2020,2020,8,11," +
            "山の日\r\n          2020,2020,9,21,敬老の日\r\n          2020,2020,9,22,秋分の日\r\n          202" +
            "0,2020,10,12,体育の日\r\n          2021,2021,1,11,成人の日\r\n          2021,2021,3,20,春分の日\r" +
            "\n          2021,2021,7,19,海の日\r\n          2021,2021,8,11,山の日\r\n          2021,2021" +
            ",9,20,敬老の日\r\n          2021,2021,9,23,秋分の日\r\n          2021,2021,10,11,体育の日\r\n     " +
            "   ")]
        public string Holiday {
            get {
                return ((string)(this["Holiday"]));
            }
            set {
                this["Holiday"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public string SundayColor {
            get {
                return ((string)(this["SundayColor"]));
            }
            set {
                this["SundayColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public string SaturdayColor {
            get {
                return ((string)(this["SaturdayColor"]));
            }
            set {
                this["SaturdayColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public string HolidayColor {
            get {
                return ((string)(this["HolidayColor"]));
            }
            set {
                this["HolidayColor"] = value;
            }
        }
    }
}
